#ifndef ALARMS_H
#define ALARMS_H


enum Alarms
{
  ALARM_LOW_BATTERY,           
  ALARM_HIGH_PRESSURE,         
  ALARM_LOW_PRESSURE,          
  ALARM_HIGH_VOLUME_PER_MINUTE,
  ALARM_LOW_VOLUME_PER_MINUTE,
  ALARM_HIGH_BREATHS_PER_MINUTE,
  ALARM_LOW_BREATHS_PER_MINUTE    
};


#endif